#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const skillsDir = path.join(root, 'skills');
const rows = [];
const categories = {
  'android-core': 'Android platform',
  'kotlin-core': 'Kotlin',
  'jetpack-compose': 'UI',
  'compose-performance': 'Performance',
  'android-architecture': 'Architecture',
  'gradle-build': 'Build',
  'firebase-core': 'Firebase',
  'firebase-auth': 'Firebase',
  'firestore': 'Firebase',
  'firebase-cloud-functions': 'Firebase',
  'firebase-messaging': 'Firebase',
  'firebase-crashlytics-analytics': 'Firebase',
  'firebase-ai-logic': 'Firebase AI',
  'room-datastore': 'Local data',
  'networking-retrofit-ktor': 'Networking',
  'dependency-injection': 'Architecture',
  'testing': 'Testing',
  'security-privacy': 'Security',
  'accessibility': 'Accessibility',
  'debugging': 'Debugging',
  'play-store-release': 'Release',
  'code-review-refactor': 'Review',
  'android-navigation-3': 'UI and Compose',
  'agp9-kotlin-migration': 'Build and migration',
  'r8-proguard-optimization': 'Release',
  'xml-to-compose-migration': 'UI and Compose',
  'edge-to-edge-adaptive-ui': 'UI and Compose',
  'firebase-emulator-ci': 'Firebase',
  'firestore-costs-quotas': 'Firebase',
  'workmanager-background-sync': 'Data and sync',
  'macrobenchmark-baseline-profiles': 'Performance',
  'dependency-upgrade-safety': 'Build and migration',
  'design-test-gate': 'Design and UX',
  'context-aware-ui-design': 'Design and UX',
  'compose-contextual-design-system': 'Design and UX',
  'screen-ux-audit': 'Design and UX',
  'ui-state-design': 'Design and UX'
};
function parse(text) {
  const end = text.indexOf('\n---', 4);
  const fm = text.slice(4, end).trim();
  const data = {};
  for (const line of fm.split(/\r?\n/)) {
    const m = line.match(/^([^:]+):\s*(.*)$/);
    if (m) data[m[1].trim()] = m[2].replace(/^['"]|['"]$/g, '').trim();
  }
  const when = (text.match(/# When to use\n\n([\s\S]*?)\n\n# Inputs to inspect/) || [,''])[1]
    .trim()
    .split(/\r?\n/)
    .map((line) => line.replace(/^-\s*/, '').trim())
    .filter(Boolean)
    .join('; ');
  return { data, when };
}
function compact(value, max = 170) {
  const text = String(value || '').replace(/\s+/g, ' ').trim();
  return text.length > max ? `${text.slice(0, max - 3).trim()}...` : text;
}
for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true }).filter(e => e.isDirectory()).sort((a,b)=>a.name.localeCompare(b.name))) {
  const file = path.join(skillsDir, entry.name, 'SKILL.md');
  const text = fs.readFileSync(file, 'utf8');
  const { data, when } = parse(text);
  const category = categories[data.name] || 'General';
  rows.push({ name: data.name, description: compact(data.description), category, path: path.relative(root, file), when: compact(when, 180) });
}
let out = '# Skill Catalog\n\nGenerated by `node scripts/generate-catalog.mjs`.\n\n| Name | Description | Category | Path | When to use |\n|---|---|---|---|---|\n';
for (const r of rows) out += `| \`${r.name}\` | ${r.description} | ${r.category} | \`${r.path}\` | ${r.when} |\n`;
fs.writeFileSync(path.join(root, 'CATEGORIES.md'), out);
console.log(`Generated CATEGORIES.md with ${rows.length} skills.`);
