#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const skillsDir = path.join(root, 'skills');
const rows = [];
const categories = {
  'android-core': 'Android platform',
  'kotlin-core': 'Kotlin',
  'jetpack-compose': 'UI',
  'compose-performance': 'Performance',
  'android-architecture': 'Architecture',
  'gradle-build': 'Build',
  'firebase-core': 'Firebase',
  'firebase-auth': 'Firebase',
  'firestore': 'Firebase',
  'firebase-cloud-functions': 'Firebase',
  'firebase-messaging': 'Firebase',
  'firebase-crashlytics-analytics': 'Firebase',
  'firebase-ai-logic': 'Firebase AI',
  'room-datastore': 'Local data',
  'networking-retrofit-ktor': 'Networking',
  'dependency-injection': 'Architecture',
  'testing': 'Testing',
  'security-privacy': 'Security',
  'accessibility': 'Accessibility',
  'debugging': 'Debugging',
  'play-store-release': 'Release',
  'code-review-refactor': 'Review'
};
function parse(text) {
  const end = text.indexOf('\n---', 4);
  const fm = text.slice(4, end).trim();
  const data = {};
  for (const line of fm.split(/\r?\n/)) {
    const m = line.match(/^([^:]+):\s*(.*)$/);
    if (m) data[m[1].trim()] = m[2].replace(/^['"]|['"]$/g, '').trim();
  }
  const when = (text.match(/# When to use\n\n([\s\S]*?)\n\n# Inputs to inspect/) || [,''])[1].trim().replace(/\n/g, '<br>');
  return { data, when };
}
for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true }).filter(e => e.isDirectory()).sort((a,b)=>a.name.localeCompare(b.name))) {
  const file = path.join(skillsDir, entry.name, 'SKILL.md');
  const text = fs.readFileSync(file, 'utf8');
  const { data, when } = parse(text);
  const category = categories[data.name] || 'General';
  rows.push({ name: data.name, description: data.description, category, path: path.relative(root, file), when });
}
let out = '# Skill Catalog\n\nGenerated by `node scripts/generate-catalog.mjs`.\n\n| Name | Description | Category | Path | When to use |\n|---|---|---|---|---|\n';
for (const r of rows) out += `| \`${r.name}\` | ${r.description} | ${r.category} | \`${r.path}\` | ${r.when} |\n`;
fs.writeFileSync(path.join(root, 'CATEGORIES.md'), out);
console.log(`Generated CATEGORIES.md with ${rows.length} skills.`);
